#!/bin/csh -f
# a simple way to test everything

set rec = recognizer.sml
set tok = tokenizer.sml

if (-f "${rec}") then
   foreach i ( tests/input/* )
	echo ==== Part 1 -- $i ====
	./run_rec ${rec} $i tests/1_recognizer
   end
else
   echo "Missing ${rec}, skipping tests."
endif

if (-f "${tok}") then
   foreach i ( tests/input/* )
	echo ==== Part 2 -- $i ====
	./run_tok ${tok} $i tests/2_tokenizer
   end
else
   echo "Missing ${tok}, skipping tests."
endif

